// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using villaApi.Services;

#nullable disable

namespace villaApi.Migrations
{
    [DbContext(typeof(VillaDBContext))]
    [Migration("20240219114523_initialMigrations")]
    partial class initialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("villaApi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("double");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreateAt = new DateTime(2024, 2, 19, 11, 45, 23, 30, DateTimeKind.Local).AddTicks(3100),
                            Details = "lorem lorem lorem lorem lorem lorem lorem lorem lorem ",
                            ImageUrl = "No pic available",
                            Name = "Pool view",
                            Occupancy = 5,
                            Rate = 300.0,
                            Sqft = 550,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreateAt = new DateTime(2024, 2, 19, 11, 45, 23, 30, DateTimeKind.Local).AddTicks(3140),
                            Details = "lorem lorem lorem lorem lorem lorem lorem lorem lorem ",
                            ImageUrl = "No pic available",
                            Name = "Mountain view",
                            Occupancy = 5,
                            Rate = 300.0,
                            Sqft = 550,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreateAt = new DateTime(2024, 2, 19, 11, 45, 23, 30, DateTimeKind.Local).AddTicks(3140),
                            Details = "lorem lorem lorem lorem lorem lorem lorem lorem lorem ",
                            ImageUrl = "No pic available",
                            Name = "Best view",
                            Occupancy = 5,
                            Rate = 300.0,
                            Sqft = 550,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreateAt = new DateTime(2024, 2, 19, 11, 45, 23, 30, DateTimeKind.Local).AddTicks(3140),
                            Details = "lorem lorem lorem lorem lorem lorem lorem lorem lorem ",
                            ImageUrl = "No pic available",
                            Name = "Beach view",
                            Occupancy = 5,
                            Rate = 300.0,
                            Sqft = 550,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
